-- auto Generated on 2019-04-11
-- DROP TABLE IF EXISTS user;
CREATE TABLE user(
	id BIGINT (15) NOT NULL AUTO_INCREMENT COMMENT 'id',
	user_name VARCHAR (50) NOT NULL DEFAULT '' COMMENT 'userName',
	email VARCHAR (50) NOT NULL DEFAULT '' COMMENT 'email',
	PRIMARY KEY (id)
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT 'user';
